export const userItems = [
  { name: "Home", links: "/", roles: ["ADMIN"] },
  {
    name: "SMS",
    links: [
      "/sendsms",
      "/smsreports",
      "/smsdlttemplates",
      "/smscampaigndetaillogs",
      "/smsAttachmentdetaillog",
    ],
    roles: ["ADMIN"],
  },
  {
    name: "Two Way SMS",
    links: ["/managekeywords", "/twowayreports", "/twowayintegration"],
    roles: ["ADMIN"],
  },
  {
    name: "RCS",
    links: [
      "/sendrcs",
      "/rcsmanagetemplate",
      "/rcssuggestionreport",
      "/rcsdeliverycampaigndetails",
      "/rcsaddtemplatercs",
      "/rcsdeliveryreport",
      "/rcsmanagebot",
    ],
    roles: ["ADMIN"],
  },
  {
    name: "WHATSAPP",
    links: [
      "/wlaunchcampaign",
      "/wlivechat",
      "/wmanagecampaign",
      "/managetemplate",
      "/wqrcode",
      "/wmanagewaba",
      "/wwhatsappconversation",
      "/wwhatsappmanageagent",
      "/wwhatsappbot",
      "/createwhatsappbot",
      "/wcampaigndetailsreport",
      "/createtemplate",
      "/wlcsetting",
      "/wwhatsappflows",
      "/wflowcreation",
      "/apicampaigninfo",
      "/wblockuser",
      "/wmmlite",
    ],
    roles: ["ADMIN"],
  },
  {
    name: "Number Lookup",
    links: ["/hlrlookup", "/lookupreports"],
    roles: ["ADMIN"],
  },
  {
    name: "App Authenticator",
    links: ["/authsettings", "/authreports"],
    roles: ["ADMIN"],
  },
  {
    name: "E-mail",
    links: ["/emailtemplate", "/emailreports"],
    roles: ["ADMIN"],
  },
  {
    name: "OBD",
    links: [
      "/obdcreatecampaign",
      "/obdmanagecampaign",
      "/obdmanagevoiceclips",
      "/obdIntegration",
    ],
    roles: ["ADMIN"],
  },
  {
    name: "IBD",
    links: [
      "/ibdcallhistory",
      "/ibdmanageexecutive",
      "/ibdivrflow",
      "/ibdsettings",
    ],
    roles: ["ADMIN"],
  },
  {
    name: "Missed Call",
    links: ["/missedcallhistory", "/missedcallsettings"],
    roles: ["ADMIN"],
  },
  {
    name: "Click-2-Call",
    links: ["/clicktohistory", "/clicktosettings"],
    roles: ["ADMIN"],
  },
  {
    name: "CallBack",
    links: ["/callback", "/addcallback", "/editcallback"],
    roles: ["ADMIN"],
  },
  {
    name: "Manage Funds",
    links: ["/recharge"],
    roles: ["ADMIN", "DIRECTUSER"],
  },
  // {
  //   name: "Admin",
  //   links: [
  //     "/manageuser",
  //     "/managedlttemplate",
  //     "/rcsmanagebot",
  //     "/managevoiceclips",
  //     "/manageplan",
  //     "/accountmanager",
  //     "/graphmain",
  //     "/graphuserwise",
  //     "/manageSMPP",
  //     "/managerouting",
  //     "/SMPPerrorcode",
  //     "/manageprefix",
  //     "/blacklist",
  //     "/managenotifications",
  //     "/CreateWhatsappTemplateAdmin",
  //   ],
  //   roles: ["ADMIN"],
  // },
  {
    name: "Manage Contacts",
    links: "/managecontacts",
    roles: ["ADMIN", "DIRECTUSER"],
  },
  {
    name: "Wish Management",
    links: "/smswishmanagement",
    roles: ["ADMIN"],
  },
  {
    name: "API Docs",
    links: "/docs",
    roles: ["ADMIN"],
  },
  {
    name: "openRoutes",
    links: [
      "/download",
      "/loginIpdetails",
      "/profile",
      "/settings",
      "/transactions",
    ],
    roles: ["ADMIN"],
  },
  {
    name: "Download",
    links: "/dummy",
    roles: ["ADMIN"],
  },
  {
    name: "openRoutes",
    links: [
      "/download",
      "/loginIpdetails",
      "/profile",
      "/settings",
      "/transactions",
    ],
    roles: ["ADMIN"],
  },
];
